### ISSUE TITLE
ActivityProxy not work in 0.9.3

### ISSUE THREAD

**Issue by Hicores** [KyuubiRan/EzXHelper#13]
ActivityProxy not work in 0.9.3, and the last available version is 0.8.8.It will open the host activity when I start my activity.
There is no Xposed Log but I found some error log in logcat.
`2022-06-08 20:43:46.799 31909-31909/? E/EzXHelper: java.lang.NoSuchMethodException
        at com.github.kyuubiran.ezxhelper.utils.MethodUtilsKt.method-_8BSV04(MethodUtils.kt:49)
        at com.github.kyuubiran.ezxhelper.utils.MethodUtilsKt.method-_8BSV04$default(MethodUtils.kt:32)
        at com.github.kyuubiran.ezxhelper.utils.parasitics.MyHandler.handleMessage(ActivityHelper.kt:528)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loopOnce(Looper.java:233)
        at android.os.Looper.loop(Looper.java:344)
        at com.tencent.rmonitor.looper.LooperProxy.run(LooperProxy.java:18)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:233)
        at android.os.Looper.loop(Looper.java:344)
        at android.app.ActivityThread.main(ActivityThread.java:8184)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)`

Android:12 API 31   ColorOS 12

**Comment by keta1** [comment]
@Hicores 你要不 帮忙 修修

**Comment by Hicores** [comment]
我不会，而且我也不知道什么原因



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年06月10日 19:48 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [KyuubiRan/EzXHelper] ActivityProxy not work in 0.9.3 (Issue #13) |

@Hicores 你要不 帮忙 修修

**Comment by YuKongA** [comment]
+1 ( 所以 miuihome 现在还是 0.8.8

`[ 2022-06-18T13:54:51.019     1000:  1461:  2163 I/LSPosed-Bridge  ] [D/RPackHook] Intent: startActivity { calling=com.miui.home:10110-26487, rc=1000-1461, requestCode=-1, startFlags=0,intent=Intent { cmp=com.miui.home/.settings.DefaultHomeSettings (has extras) }, extras={ com_yuk_miuihome_intent_proxy:(android.content.Intent)subIntent#1:{ Intent { cmp=com.miui.home/com.yuk.miuihome.view.HookSettingsActivity (has extras) }, extras={ miui.extra.split.PID:(java.lang.Integer)24245 } } } }
[ 2022-06-18T13:54:51.020     1000:  1461:  2163 I/LSPosed-Bridge  ] [D/RPackHook] component:no:null
[ 2022-06-18T13:54:51.074    10110: 26487: 26487 I/LSPosed-Bridge  ] Crash unexpectedly: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.miui.home/com.miui.home.settings.DefaultHomeSettings}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.ActionBar.setTitle(int)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3778)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3952)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:107)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2286)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8250)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.ActionBar.setTitle(int)' on a null object reference
	at com.miui.home.settings.DefaultHomeSettings.onCreate(DefaultHomeSettings.java:69)
	at android.app.Activity.performCreate(Activity.java:8294)
	at android.app.Activity.performCreate(Activity.java:8258)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1341)
	at com.github.kyuubiran.ezxhelper.utils.parasitics.MyInstrumentation.callActivityOnCreate(ActivityHelper.kt:349)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3758)
	... 12 more
[ 2022-06-18T13:54:51.432    10110: 26487: 26487 I/LSPosed-Bridge  ] MiuiHome: Crash happened
`

**Comment by KyuubiRan** [comment]
那我找个时间回滚一下吧

**Comment by KyuubiRan** [comment]
哦 我找到问题了 有个field应该是static的 find错了

**Comment by KyuubiRan** [comment]
已修复 请更新到0.9.7版本
